-- MySQL Script generated by MySQL Workbench
-- sex 07 mai 2021 12:07:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbCadastroProdutos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbCadastroProdutos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbCadastroProdutos` ;
USE `dbCadastroProdutos` ;

-- -----------------------------------------------------
-- Table `dbCadastroProdutos`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbCadastroProdutos`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `dsCategoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 10002;


-- -----------------------------------------------------
-- Table `dbCadastroProdutos`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbCadastroProdutos`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nmProduto` VARCHAR(120) NOT NULL,
  `dsProduto` VARCHAR(255) NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `nmProduto_UNIQUE` (`nmProduto` ASC) VISIBLE,
  INDEX `fk_Produto_Categoria1_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `dbCadastroProdutos`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10002;


-- -----------------------------------------------------
-- Table `dbCadastroProdutos`.`Imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbCadastroProdutos`.`Imagem` (
  `idImagem` INT NOT NULL AUTO_INCREMENT,
  `dsImagem` VARCHAR(255) NULL,
  `nomeDoArquivo` VARCHAR(120) NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idImagem`),
  UNIQUE INDEX `nomeDoArquivo_UNIQUE` (`nomeDoArquivo` ASC) VISIBLE,
  INDEX `fk_Imagem_Produto_idx` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Imagem_Produto`
    FOREIGN KEY (`idProduto`)
    REFERENCES `dbCadastroProdutos`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10002;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;